# syntax=docker/dockerfile:1

FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /app/bin/account_producer ./cmd/account_producer

FROM gcr.io/distroless/base-debian12
WORKDIR /app/cmd/account_producer

COPY --from=builder /app/configs /app/configs
COPY --from=builder /app/assets /app/assets
COPY --from=builder /app/bin/account_producer ./account_producer

ENTRYPOINT ["./account_producer"]

